version: '3'

services:
  db:
    restart: unless-stopped
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'mydatabaseuser'
      MYSQL_PASSWORD: 'mypassword'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    expose:
      - 3306

  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /usr/src/app/web-entrypoint.sh
    volumes:
      - static_volume:/usr/src/app/fake_nasa/static
      - media_volume:/usr/src/app/fake_nasa/media
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/fake_nasa/static
      - media_volume:/usr/src/app/fake_nasa/media
    depends_on:
      - web

volumes:
  static_volume: { }
  media_volume: { }
  mysql_data: { }